/**
 * JavaScript / Python model parity.
 *
 * Dependency-free. Run with:  node tests/ml-parity.test.js
 *
 * utils/ml-classifier.js reimplements, by hand, the transform that scikit-learn fitted
 * in ml/train.py: the tokenizer, the n-gram expansion, sublinear term frequency, the IDF
 * weighting, L2 normalisation and the softmax. Nothing enforces that the two agree.
 *
 * A mistake on the JavaScript side does not throw. It produces slightly different
 * probabilities, the extension starts keeping and dropping different sentences, and the
 * accuracy printed by the training run stops describing what ships. This test compares
 * the JavaScript output against predictions recorded by train.py at export time, so that
 * silent divergence becomes a failure.
 *
 * The fixture is regenerated by:  cd ml && python train.py
 */
const fs = require('fs');
const path = require('path');
const { PromptMeterML } = require('../utils/ml-classifier.js');

const FIXTURE = path.join(__dirname, 'ml-parity.json');

// The export is lossy on purpose: coefficients are rounded to five decimals and those
// under MIN_ABS_COEF are dropped entirely, to keep the shipped file small. That bounds
// how closely the two implementations can agree, so an exact match is not the property
// to test for. This budget is wide enough to absorb the approximation and far too narrow
// to hide a real difference in the transform -- a wrong n-gram order or a missed
// sublinear tf moves probabilities by whole percentage points, not thousandths.
const TOLERANCE = 2e-3;

// What actually matters is that the approximation never changes a decision. These are
// the thresholds condense.js compares against; a probability may drift a little, but it
// must not drift across one of these.
const ML_KEEP_VETO = 0.80;
const ML_DROP_PROPOSE = 0.92;

let passed = 0;
const failures = [];

const record = (name, ok, detail) => {
    if (ok) { passed++; return; }
    failures.push(`${name}\n      ${detail}`);
};

if (!fs.existsSync(FIXTURE)) {
    console.error(`Missing ${path.relative(process.cwd(), FIXTURE)}.`);
    console.error('Regenerate it with:  cd ml && python train.py');
    process.exit(1);
}

const fixture = JSON.parse(fs.readFileSync(FIXTURE, 'utf8'));

record('a trained model is loaded', PromptMeterML.isAvailable(),
    'PromptMeterML.isAvailable() returned false');

record('the exported label set matches',
    JSON.stringify(PromptMeterML.info().labels) === JSON.stringify(fixture.labels),
    `got ${JSON.stringify(PromptMeterML.info().labels)}, fixture has ${JSON.stringify(fixture.labels)}`);

// The n-gram expansion has to produce sklearn's features, in sklearn's order.
const grams = PromptMeterML.features(['alpha', 'beta', 'gamma']);
const config = PromptMeterML.config();
if (config.ngramMax > 1) {
    record('bigrams are joined with a single space',
        grams.includes('alpha beta') && grams.includes('beta gamma'),
        `got ${JSON.stringify(grams)}`);
    record('unigrams are still emitted alongside bigrams',
        grams.includes('alpha') && grams.includes('gamma'),
        `got ${JSON.stringify(grams)}`);
} else {
    record('unigram config emits only unigrams',
        grams.length === 3, `got ${JSON.stringify(grams)}`);
}

let worst = 0;
let worstCase = '';
let abstained = 0;

fixture.cases.forEach(testCase => {
    const result = PromptMeterML.classify(testCase.text);

    // An abstention is a legitimate answer, but only for text the model cannot see;
    // every fixture row came from the training corpus, so it should carry evidence.
    if (!result) {
        abstained += 1;
        return;
    }

    let expectedBest = 0;
    testCase.scores.forEach((score, index) => {
        if (score > testCase.scores[expectedBest]) expectedBest = index;
    });

    record(`[label] ${testCase.text.slice(0, 48)}`,
        result.label === fixture.labels[expectedBest],
        `got "${result.label}", expected "${fixture.labels[expectedBest]}"`);

    fixture.labels.forEach((label, index) => {
        const delta = Math.abs(result.scores[label] - testCase.scores[index]);
        if (delta > worst) { worst = delta; worstCase = testCase.text; }
    });

    // The decision, not the probability, is what the optimizer consumes: both sides must
    // land on the same side of each threshold.
    const keepIndex = fixture.labels.indexOf('IMPORTANT');
    const referenceKeep = testCase.scores[keepIndex];
    const actualKeep = result.scores.IMPORTANT;

    record(`[veto] ${testCase.text.slice(0, 40)}`,
        (referenceKeep >= ML_KEEP_VETO) === (actualKeep >= ML_KEEP_VETO),
        `keep ${actualKeep.toFixed(4)} vs ${referenceKeep.toFixed(4)} straddles ${ML_KEEP_VETO}`);

    record(`[propose] ${testCase.text.slice(0, 40)}`,
        ((1 - referenceKeep) >= ML_DROP_PROPOSE) === ((1 - actualKeep) >= ML_DROP_PROPOSE),
        `removable ${(1 - actualKeep).toFixed(4)} vs ${(1 - referenceKeep).toFixed(4)} ` +
        `straddles ${ML_DROP_PROPOSE}`);
});

record('probabilities match scikit-learn within export rounding', worst < TOLERANCE,
    `largest difference ${worst.toExponential(3)} on ${JSON.stringify(worstCase)} ` +
    `(tolerance ${TOLERANCE})`);

console.log(`\nLargest probability difference: ${worst.toExponential(3)} (tolerance ${TOLERANCE})`);
console.log(`Abstentions: ${abstained} of ${fixture.cases.length}`);
console.log(`\n${passed} passed, ${failures.length} failed`);

if (failures.length > 0) {
    console.log('\nFailures:\n');
    failures.forEach((failure, index) => console.log(`  ${index + 1}. ${failure}\n`));
    process.exit(1);
}
console.log('\nJavaScript and scikit-learn agree.');
